version: '3.8'
services:
  postgres:
    image: postgres:15
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: master
      POSTGRES_PASSWORD: master
      TZ: 'Asia/Seoul'
    depends_on:
      - redis

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
